### ISSUE TITLE
[Feat] 홈 뷰 UI 구현 

### ISSUE THREAD

**Issue by minnnidev** [SOPT-31th-Joint-Seminar-5/Client-iOS#1]
## 🛠 Issue

홈 뷰 UI 구현

## 📋 To-do

- [x] 상단 bar UIView 이용하여 구현
- [x] UICollectionView + UIPageViewController로 tab bar 구현
- [x] UICollectionView로 카드 부분 구현

**Comment by minnnidev** [comment]
뭔가 잘못된 것 같아서 그냥 브랜치를 뿌섯다. . .. ...
