### ISSUE TITLE
[Chore] API 템플릿 수정

### ISSUE THREAD

**Issue by meltsplit** [SOPT-31th-Joint-Seminar-5/Client-iOS#16]
## 🛠 Issue
API 템플릿 수정

## 📋 To-do
- [x] Request 모델 수정
- [x] API 파일 추가
- [x] Service 객체 수정
