### ISSUE TITLE
[Feat] 러닝뷰 하단 런게이지 기능 구현

### ISSUE THREAD

**Issue by meltsplit** [SOPT-31th-Joint-Seminar-5/Client-iOS#19]
## 🛠 Issue
- 러닝뷰 하단 런게이지 기능 구현

## 📋 To-do
- [x] RunGauge 스택뷰 CustomView 로 구현
- [x] RunGauge 뷰 구조 개선
- [x] 스택뷰에서 준 정보에 따라 RunGuage 뷰 가로 길이 결정
- [x] 시간에 따라 색상 변하는 기능 구현...!!!
