### ISSUE TITLE
[Feat] 홈뷰 API 연동

### ISSUE THREAD

**Issue by minnnidev** [SOPT-31th-Joint-Seminar-5/Client-iOS#20]
## 🛠 Issue

홈뷰 API 연동

## 📋 To-do

- [x] 유저 달리기 정보 API 연동
- [x] 사진 넣기
- [x] 나머지 탭들 더미데이터 구현
- [x] 좋아요 동작 구현(API 연동 제외)
- [x] 운동명 제목 색 변경
