### ISSUE TITLE
[Feat] Circle ProgressBar 구현

### ISSUE THREAD

**Issue by meltsplit** [SOPT-31th-Joint-Seminar-5/Client-iOS#23]
## 🛠 Issue
- Circle ProgressBar 구현 

## 📋 To-do
- [x] UIBezierPath 통해 반원 그리기
- [x]  UIBeizerPath와 같은 path의 CAShapeLayer 만들기
- [x] CAShapeLayer에 애니메이션 기능 추가하기
- [x] 러닝뷰에서 시간 데이터 CAShapeLayer와 연동시키기
