### ISSUE TITLE
[Feat] 러닝뷰 Animation 기능 구현

### ISSUE THREAD

**Issue by meltsplit** [SOPT-31th-Joint-Seminar-5/Client-iOS#6]
## 🛠 Issue
- 러닝뷰 Animation 기능을 구현해보자.

## 📋 To-do
- [x] voice.json 파일 Lottie로 넣기
- [x] 직선 progress 바 시간에 따라 증가시키기
- [x] Timer 기능 구현
